### ISSUE TITLE
Laravel 5.0

### ISSUE THREAD

**Issue by asika32764** [smstw/windwalker-joomla-rad#19]
蠻多東西可以參考
https://laravel-news.com/2014/08/new-laravel-4-3-features/

Scheduler
https://laravel-news.com/2014/11/laravel-5-scheduler/

Attribute Casting
http://laravel.com/docs/master/eloquent#attribute-casting

New Validation
http://laravel.com/docs/master/validation#controller-validation

**Comment by skylying** [comment]
想偷來用嗎

**Comment by asika32764** [comment]
See https://github.com/ventoviro/windwalker-joomla-rad/issues/147
