### ISSUE TITLE
找不到 Cache_Lite 類別

### ISSUE THREAD

**Issue by gundamew** [smstw/windwalker-joomla-rad#25]
在 Joomla! 根目錄下，依照 [ventoviro/windwalker-joomla-rad](https://github.com/ventoviro/windwalker-joomla-rad#generate-a-new-extension) 文件執行下列指令：

``` bash
php bin/windwalker generator init com_flower sakura.sakuras -c admin -v
```

得到下列錯誤訊息：

``` bash
Warning: require_once(Cache/Lite.php): failed to open stream: No such file or directory in /Users/bschen/dev_apps/joomla/libraries/joomla/cache/storage/cachelite.php on line 77

Fatal error: require_once(): Failed opening required 'Cache/Lite.php' (include_path='.:') in /Users/bschen/dev_apps/joomla/libraries/joomla/cache/storage/cachelite.php on line 77
```

使用 Joomla! 3.4

目前可以用下列方式解決這個問題：
1. 另外自行安裝 [pear/Cache_Lite](https://github.com/pear/Cache_Lite)
2. 將 cachelite.php#60 的 `$this->initCache($cloptions);` 註解掉

**Comment by asika32764** [comment]
我現在完全無法重現這個狀況

**Comment by gundamew** [comment]
@asika32764 是全新安裝的 Joomla! 和 windwalker-joomla-rad 嗎？

**Comment by asika32764** [comment]
全新安裝的 3.4.0 & 3.4.1 皆無法重現

![150413-0006](https://cloud.githubusercontent.com/assets/1639206/7113623/3bd94ea8-e208-11e4-84da-78f391c04cea.jpg)

**Comment by asika32764** [comment]
@gundamew 你再試一次最新的環境看看，如果還有的話，幫我在 require 那一行丟 Exception 出去，然後複製 backtrace 貼上來

**Comment by michael520** [comment]
Could not connect to MySQL 的情形，如果沒記錯的話。
MySQL host 修改至 127.0.0.1 試看看。

**Comment by asika32764** [comment]
那是 mysql.sock 的問題，因為我的是新的 XAMPP 環境

建立軟連結就解決了

**Comment by asika32764** [comment]
重新跑是這樣

![150413-0007](https://cloud.githubusercontent.com/assets/1639206/7113726/2f0253ae-e209-11e4-83da-7192ec6b4680.jpg)

**Comment by gundamew** [comment]
@asika32764 我重新安裝以後也沒有再遇到問題了 orz

除了 `bin/windwalker` 變成 `bin/windwalker.php` 以外，過程和結果都如同預期

**Comment by asika32764** [comment]
看來沒問題了，關閉
