### ISSUE TITLE
[Test] Helper 

### ISSUE THREAD

**Issue by bblurock** [smstw/windwalker-joomla-rad#26]
### 2/25 第一次 Review

@michael520
- [x] DateHelper.php
- [x] PathHelper.php
- [x] XmlHelper.php

@gundamew 
- [x] HtmlHelper.php
- [x] UriHelper.php

@bblurock
- [x] CurlHelper.php
- [x] LanguageHelper.php
- [x] ModalHelper.php

@LeoOnTheEarth 
- [x] AssetHelper.php
- [x] ProfilerHelper.php
- [x] ReflectionHelper.php
- [x] JContentHelper.php

**Comment by skylying** [comment]
也分一點給我做吧

**Comment by LeoOnTheEarth** [comment]
@skylying 你自己認領 Helper 之外的吧
先丟個 PR 上來看看

**Comment by skylying** [comment]
你說別的 issue  咩?

**Comment by LeoOnTheEarth** [comment]
> 你說別的 issue 咩?

是寫測試啦

你要解別的 issue 也歡迎啦

**Comment by skylying** [comment]
所以 Helper 以外是什麼意思我不太懂, 有 issue 對照嗎?

**Comment by LeoOnTheEarth** [comment]
參考一下這邊的東西吧

https://github.com/smstw/windwalker-joomla-rad/tree/dev-2.1/test

我講的測試是 Unit Test (單元測試)
要對 https://github.com/smstw/windwalker-joomla-rad/tree/dev-2.1/src 底下的 class 寫單元測試

目前寫單元測試的工作才剛開始，先以完成 Helper 類的為主
issue 的話會看工作情形來開

你要幫忙的話，可以開個 issue 告知說要為哪個 class 寫單元測試 :-)

**Comment by skylying** [comment]
誒? 這是從頂層 windwalker-rad fork 來的, 你們現在 smstw 要用的, 那先不要太正式的好了, 我本來以為是 windwalker rad 而已, 不要拖累到你們現在公司的進度比較好一點

@LeoOnTheEarth 好滴, 我來看看嘿
