### ISSUE TITLE
在 travis 裡很詭異的怪象

### ISSUE THREAD

**Issue by LeoOnTheEarth** [smstw/windwalker-joomla-rad#30]
https://travis-ci.org/smstw/windwalker-joomla-rad/jobs/55769461#L251

這裡帶到 `testPivotFromPrefix` 的參數如下
`('pr_', array(123, 223, 223), null, array(123, 223))`

第二和第四個參數原本應該是 key-value 的 array，但是不知道為什麼 key 都不見了...

**Comment by LeoOnTheEarth** [comment]
啊，沒事，帶到 `testPivotFromPrefix` 是和預期的一樣
那看來是別的問題

繼續 debug 中...

**Comment by LeoOnTheEarth** [comment]
找到問題點了，問題出在這一行中的 `$key2`

https://github.com/smstw/windwalker-joomla-rad/blob/dev-2.1/src/Helper/ArrayHelper.php#L210

不知道為什麼在 travis 裡面
用 PHP 5.3 跑的結果 `$key2` 一直都是空字串
這就造成 pivot 的結果一直都是空的

**Comment by LeoOnTheEarth** [comment]
@asika32764 麻煩你看一下

另外我不太確定 `Utf8String::substr` 是放在哪個檔案
他被定義在好多地方 =_=...

**Comment by asika32764** [comment]
Fixed
