### ISSUE TITLE
[Test] DI

### ISSUE THREAD

**Issue by skylying** [smstw/windwalker-joomla-rad#41]
- [ ] ContainerTest
- [ ] ServiceProviderTest

**Comment by asika32764** [comment]
測試前把這個 PR port 過來
https://github.com/ventoviro/windwalker-joomla-rad/pull/118

另外，只要測試 class 內有的 method 即可，parent 的 method 應該由 parent 來 test.

**Comment by skylying** [comment]
這麼巧剛好跟老外選到同一個

**Comment by asika32764** [comment]
他只是改一個 3.4.1 上發生的 bug，我們也會需要這個更新，所以先更新完再寫 test 較保險

**Comment by skylying** [comment]
parent 是指什麼? `JoomlaContainer` 嗎?

**Comment by asika32764** [comment]
YES

2015-04-07 23:41 GMT+08:00 Tim Lin notifications@github.com:

> parent 是指什麼? JoomlaContainer 嗎?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smstw/windwalker-joomla-rad/issues/41#issuecomment-90613487
> .

## 

Best Regard

## Simon Asika | Kwang Po Tung | 董冠伯
- Founder: Asikart Extension http://ext.asikart.com/
- CTO: SMS Taiwan http://www.bm-sms.com.tw/
- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by skylying** [comment]
> 測試前把這個 PR port 過來

port 這個動詞是什麼? 
是說我要怎樣弄過來, 把它改的 copy 一份嗎? 因為那個 PR 不是 smstw/windwalker-joomla-rad 的
我不太知道怎樣弄

**Comment by asika32764** [comment]
老外很常用，我也很難說明，大概就是接過來的意思 port ... from ...

通常是直接 copy 一份，cherry pick 也可以

**Comment by skylying** [comment]
ok, 我在 PR #42 一起解決

**Comment by asika32764** [comment]
我找到解釋了，porting 的中文翻譯叫「移植」

**Comment by skylying** [comment]
很潮誒
