### ISSUE TITLE
"Windwalker\String\String" 路徑不正確

### ISSUE THREAD

**Issue by LeoOnTheEarth** [smstw/windwalker-joomla-rad#51]
在寫 unitTest 時
`Windwalker\String\String` 這個 class 預期應該要是 `libraries/windwalker/src/String/String.php` 這個檔案，但是得到的是 `libraries\windwalker\vendor\windwalker\string\String.php` 這個檔案

**Comment by asika32764** [comment]
目前有產生什麼錯誤嗎？

**Comment by LeoOnTheEarth** [comment]
看起來是 autoload 的問題...

`asika/muse` 依賴 `windwalker/utilities`
`windwalker/utilities` 依賴 `windwalker/string`

**Comment by LeoOnTheEarth** [comment]
問題是在 RAD 裡的 `Windwalker\String\String` 和 `Windwalker` 裡的 `Windwalker\String\String` 有衝突
有必要在 RAD 裡多放一個 `Windwalker\String\String` 嗎?

**Comment by asika32764** [comment]
在哪個地方會出問題？

**Comment by LeoOnTheEarth** [comment]
目前完全不能使用 RAD 裡的 `Windwalker\String\String`
被 autoload 導到 `libraries\windwalker\vendor\windwalker\string\String.php` 的 `Windwalker\String\String` 去了

**Comment by asika32764** [comment]
RAD 內的是很久前就寫好的，2.1 以後應該是要改用 utilities 內的 String

由於 PHP7 也不能用型態名稱當 class ，所以也要改用 Utf8String 或 StringHelper 

我需要知道你在寫哪一個 class 的 test 出的問題

**Comment by LeoOnTheEarth** [comment]
我是要寫 RAD 裡 `Windwalker\String\String` 的 unit test
所以要把它移除嗎?

**Comment by asika32764** [comment]
先保留，等多數 unittest 都寫完了再移除，這樣才知道有哪些相依要修改

除非直接影響到其他 class 的運作不然目前看起來 untilities 內的 String 可以正常的取代他的功能

**Comment by asika32764** [comment]
先幫我在 String 上面標

```
@deprecated  Use \Windwalker\Utilities\StringHelper instead.
```

**Comment by LeoOnTheEarth** [comment]
這個 class 在 dev-2.1 這個 branch 裡面是完全無法使用...
autoload 不會去使用 `libraries/windwalker/src/String/String.php` 這個檔案

另外我看到在 `libraries\windwalker\vendor\windwalker\string\String.php` 這個檔案裏面有 `Windwalker\String\String` 的 class
autoload 真正使用的 `Windwalker\String\String` 是在這個檔案裏面的
而 `Windwalker\String\String` 是繼承 `Windwalker\Utilities\StringHelper`

這點我想也是要注意的地方
如果某個地方出問題，是完全不會 trace 到 RAD 裡的 `Windwalker\String\String` class

**Comment by asika32764** [comment]
所以這代表目前 Utilities 內的 String 可以正常的取代 RAD 內的 String 正常使用阿，如果其他 test 寫完都沒問題了，RAD 內的 String 就可以刪了

**Comment by asika32764** [comment]
已在 https://github.com/smstw/windwalker-joomla-rad/pull/24 處理中
