### ISSUE TITLE
[Discuss] DataMapper 的特性

### ISSUE THREAD

**Issue by asika32764** [smstw/windwalker-joomla-rad#56]
目前有人遇到 DataMapper id = null 時的問題，其實這是原先設計的特性，不過連我都常常踩雷就是了

原先的設定是 `findOne()` 不帶參數會返回第一筆資料

要問一下大家，有沒有想要做什麼調整? 例如把預設值設為 `false`，當 id = null 或 '' 時，就 return 空 Data 等等

Joomla 另外有一種設計，$id = null 會變成 `id = NULL` 的 SQL，這也是另一種方法可以避免取到第一筆資料

大家可以討論看看

**Comment by bblurock** [comment]
我是覺得 等於 null 回傳空 Data 比較直覺

**Comment by asika32764** [comment]
那要從框架改，要一陣子，RAD 2.1 可能還無法用上

**Comment by asika32764** [comment]
Implemented in https://github.com/ventoviro/windwalker-database/blob/master/Query/QueryHelper.php#L192
