### ISSUE TITLE
[Feature] Controller Refactor

### ISSUE THREAD

**Issue by asika32764** [smstw/windwalker-joomla-rad#64]
## Redirect
- [x] 根據目前的使用經驗，還是原本的 `setRedirect()` 比較好用，這部分改回去應該是不會破壞向下相容
## HMVC
- [ ] 目前用起來卡卡，但可以正常運作，看還能不能調的更流暢
## 預先產生在元件 template 內
- [ ] 方便修改用，這需要討論

**Comment by LeoOnTheEarth** [comment]
提一下今天發現可以改善的點

https://github.com/smstw/windwalker-joomla-rad/blob/dev-2.1/src/Controller/Controller.php#L392-L407

``` php
try
{
    $model = $container->get($modelKey, $forceNew);
}
catch (\InvalidArgumentException $e)
{
    $container->share(
        $modelKey,
        function(Container $container) use($modelName, $config)
        {
            return new $modelName($config, $container, null, $container->get('db'));
        }
    );
    $model = $container->get($modelKey);
}
```

這邊的 `try..catch` 成本會不會太高?
要不要先用 `$container->exists()` 判斷 service 存不存在
不存在時才把 service 放到 `$container` 內

另一點是在 `catch` 內沒有用到 `$forceNew` 的參數
是表示新增的 Model 是不需要 `$forceNew` 的嗎?

**Comment by asika32764** [comment]
那個年代 Joomla Container 還沒有 exists ，現在才有，可以改過去

因為 catch 內的 model 一定是 new，沒有其他狀況

**Comment by LeoOnTheEarth** [comment]
喔，我沒看到有直接 new 一個 Model 出來

那我先改成用 `exists` 判斷

**Comment by asika32764** [comment]
New Redirect Rules
e5f160d6724ce737c37138ce6a50d2e9434fde18

**Comment by asika32764** [comment]
https://github.com/ventoviro/windwalker-joomla-rad/issues/141
